model_list:
  - model_name: llama-3.1-8b-instant
    litellm_params:
      provider: groq
      model: llama-3.1-8b-instant
      api_key: ${GROQ_API_KEY}

  - model_name: gpt-oss-120b
    litellm_params:
      provider: groq
      model: openai/gpt-oss-120b
      api_key: ${GROQ_API_KEY}

  - model_name: gpt-oss-20b
    litellm_params:
      provider: groq
      model: openai/gpt-oss-20b
      api_key: ${GROQ_API_KEY}

server_settings:
  host: "0.0.0.0"
  port: 4000
  api_base: "/v1"
  telemetry: false

general_settings:
  enable_spend_logging: true
  verbose: true
  master_key: "super_admin_key_123"
  log_level: "info"

logging:
  file: "/workspace/Oppen_Web_UI/litellm/litellm.log"
  level: INFO
